const express = require('express');
const fs = require('fs');
const path = require('path');

const { get } = require('../db');

const {
  authenticate,
  authorize,
} = require('../middleware/auth');

const { decrypt } = require('../utils/encryption');
const { logAction } = require('../utils/audit');

const router = express.Router();

const UPLOAD_DIR = path.join(
  __dirname,
  '..',
  '..',
  'uploads'
);

/**
 * GET /api/evidence/:fileId
 *
 * Retrieves and decrypts an evidence file.
 */
router.get(
  '/:fileId',
  authenticate,
  authorize(
    'ADMINISTRATOR',
    'COUNSELLOR'
  ),
  async (req, res) => {
    try {
      const evidence = await get(
        `SELECT *
         FROM evidence
         WHERE "fileId" = $1`,
        [req.params.fileId]
      );

      if (!evidence) {
        return res.status(404).json({
          error: 'Evidence file not found',
        });
      }

      const caseRow = await get(
        `SELECT *
         FROM cases
         WHERE "reportId" = $1`,
        [evidence.reportId]
      );

      if (
        req.user.role === 'COUNSELLOR' &&
        caseRow?.assignedToId !== req.user.id
      ) {
        return res.status(403).json({
          error:
            'You are not assigned to this case',
        });
      }

      /*
       * filePath is generated by the server.
       * basename prevents path traversal if the database
       * ever contains an unexpected value.
       */
      const storedName = path.basename(
        evidence.filePath
      );

      const fullPath = path.join(
        UPLOAD_DIR,
        storedName
      );

      if (!fs.existsSync(fullPath)) {
        return res.status(404).json({
          error:
            'File missing from storage',
        });
      }

      const encryptedContent =
        fs.readFileSync(
          fullPath,
          'utf8'
        );

      const decryptedBase64 =
        decrypt(
          encryptedContent,
          evidence.fileIv,
          evidence.fileTag
        );

      const buffer = Buffer.from(
        decryptedBase64,
        'base64'
      );

      await logAction({
        userId: req.user.id,
        action:
          'Viewed/downloaded evidence file',
        affectedRecordId:
          evidence.fileId,
      });

      res.setHeader(
        'Content-Type',
        evidence.mimeType
      );

      const safeFilename =
        path.basename(
          evidence.originalName
        ).replace(/["\r\n]/g, '_');

      res.setHeader(
        'Content-Disposition',
        `inline; filename="${safeFilename}"`
      );

      return res.send(buffer);
    } catch (error) {
      console.error(error);

      return res.status(500).json({
        error:
          'Failed to decrypt evidence file',
      });
    }
  }
);

module.exports = router;